Repository habx/aws-mq-cleaner, pull requests merged in 2022-03, with the labels that each got.

#366 APP-28465: feat(circleci): update golang build, and switch to custom orbs
  .circleci/config.yml
  .golangci.yml
  .goreleaser.yaml
  Dockerfile
  commands/root.go
  commands/root_test.go
  commands/sns/command.go
  commands/sns/command_test.go
  commands/sns/flags.go
  commands/sqs/command.go
  commands/sqs/command_test.go
  commands/sqs/flags.go
  docs/main.go
  flags/flags.go
  go.mod
  go.sum
  helpers/aws.go
  helpers/utils.go
  logger/logger.go
  logger/logger_test.go
  time/time.go
  time/time_test.go
Labels: diff-d, diff-, diff-a, diff-b

#369 Syncing dev with v1.4.1
  .circleci/config.yml
Labels: automerge

#370 APP-28494: chore/1.4/fix ci
  .circleci/config.yml
Labels: automerge, autorelease

#371 Syncing dev with v1.4.2
  .circleci/config.yml
Labels: automerge
