Repository habx/aws-mq-cleaner, pull requests merged in 2022-04, with the labels that each got.

#373 APP-28737: Various improvements
  commands/sns/command.go
  commands/sqs/command.go
  go.mod
  go.sum
Labels: automerge, autorelease-group, diff-

#375 APP-28803: chore(logger): Simplifying config
  logger/logger.go
Labels: automerge

#377 APP-28974: feat(core): limit AWS requests concurrency
  commands/sns/command.go
  commands/sqs/command.go
Labels: automerge, autorelease

#378 APP-28975: Delete dead letter queues automatically
  .circleci/config.yml
  commands/sqs/command.go
  commands/sqs/command_test.go
Labels: automerge, autorelease

#382 APP-29156: chore: remove const for max sum
  commands/sqs/command.go
Labels: automerge
